version: '3.8'

services:
  api:
    build: .
    container_name: shop_api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/shop?schema=public"
    depends_on:
      - db
    command: sh -c "npx prisma db push && npm run start:dev"

  db:
    image: postgres:15
    container_name: shop_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql